# Generated by Django 5.2.6 on 2026-01-13 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(default="Untitled Event", max_length=150),
        ),
        migrations.AlterField(
            model_name="event",
            name="venue",
            field=models.CharField(default="TBD", max_length=200),
        ),
    ]
