# Generated by Django 5.2.6 on 2026-01-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_ticket_user_remove_ticket_uuid_ticket_buyer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="event",
            name="is_hot",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="ticket_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
