# Generated by Django 5.2.6 on 2026-01-20 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_event_description_event_is_hot_event_ticket_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="restaurant",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="service",
            name="provider",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="service",
        ),
        migrations.AddField(
            model_name="event",
            name="total_tickets",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ticket",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="ticket",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="core.ticket",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="invitation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.DeleteModel(
            name="Commission",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Restaurant",
        ),
        migrations.DeleteModel(
            name="Service",
        ),
    ]
